---
title: "Good Reads Books"
output: html_document
---

---
```{r loadpackages, message=FALSE, warning=FALSE, echo=FALSE}

library(tidyverse)
library(scales)
library(unglue)
library(data.table)
library(janitor)
library(broom)
library(ggplot2)
library(reshape2)

```

```{r intro, warning=FALSE, echo=FALSE, message=FALSE}

library(usethis)
use_git_config(user.name = "orla-c", 
               user.email = "s1942599@ed.ac.uk")

```


```{r readcsv, warning=FALSE, echo=FALSE, message=FALSE}

goodreads <- read_csv("/cloud/project/books.csv")
goodreads <- goodreads[complete.cases(goodreads),]

view(goodreads)  
print(goodreads)
```

```{r, count}
goodreads %>%
  count(authors)%>%
  arrange(desc(n))

goodreads %>%
  count(publisher)%>%
  arrange(desc(n))

goodreads %>%
  count(language_code)%>%
  arrange(desc(n))

lang <-table(goodreads$language_code)
lang

```


```{r, english}
books_eng <- goodreads %>%
  filter(language_code %in% c("eng", "en-US", "en-CA", "en-GB"))

print(books_eng)

```


```{r}
jkrowling <- books_eng%>%
  filter(authors %like% "J.K. Rowling")
jkrowling
```

```{r, linear_regression_model}

m_br_rt <- lm(average_rating ~ ratings_count, data = books_eng)
tidy(m_br_rt)
glance(m_br_rt)$r.squared


```


```{r, plot_ratings_against_jkrowling, fig.height=20, fig.width=15}
jkrowling%>%
  ggplot(mapping = aes(x = title, y = average_rating)) +
  geom_bar(stat = "identity", fill = "violet") +
  labs(x = "Title", 
       y = "Average Rating",
       title = "Harry Potter Ratings") +
  theme(axis.text.x = element_text(angle = 45))


```


```{r}
```


```{r}
```


```{r}
```

